# Generated by Django 3.2.6 on 2021-08-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_app', '0002_alter_advert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
    ]
