# Generated by Django 3.2.6 on 2021-08-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_app', '0003_alter_advert_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Deleted'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='published_at',
            field=models.DateTimeField(verbose_name='Published At'),
        ),
    ]
