# Generated by Django 3.2.6 on 2021-08-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_app', '0005_alter_advert_published_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'permissions': [('moderate_advert', 'Can moderate the advert and change statuses')], 'verbose_name': 'Advert', 'verbose_name_plural': 'Adverts'},
        ),
    ]
